# Do you want to restrict bank commands to bank plots (requires Towny)
restrictToBankPlot: false
messages:
  info-balance: '<white>You have a total balance of <total> Gold (Bank: <bank> | Inventory: <inv>)'
  info-withdraw: '<white>You have withdrawn <amount> Gold'
  info-deposit: '<white>You have deposited <amount> Gold'
  info-sendmoneyto: 'You''ve sent <gold><amount> Gold</gold> to <target>!'
  info-moneyreceived: 'You have received <gold><amount> Gold</gold> from <sender>!'
  info-sender-moneyset: 'Balance of <player> set to <gold><amount>!'
  info-target-moneyset: 'Your balance was set to <amount>!'
  info-sender-addmoney: 'Added <gold><amount> Gold to the balance of <player>!'
  info-target-addmoney: '<amount> was added to your balance!'
  info-sender-remove: 'Removed <gold><amount> Gold from the balance of <player>!'
  info-target-remove: '<amount> was removed from your balance!'
  help-deposit: 'You need to specify how much gold you want to deposit! Usage: /bank deposit <gold | all>'
  help-withdraw: 'You need to specify how much gold you want to withdraw! Usage: /bank withdraw <gold | all>'
  warning-update: 'You are using an outdated version of the plugin. Please update to the latest version.'
  warning-drops: 'Items that didn''t fit into your inventory were dropped!'
  error-bankplot: 'You have to be on a Bank Plot to use this command!'
  error-noplayer: 'No player found!'
  error-zero: 'You can''t withdraw or deposit 0 gold!'
  error-negative: 'You can''t withdraw, deposit or transfer a negative amount of gold!'
  error-notenough: 'You don''t have enough gold!'
  error-payyourself: 'You cannot send money to yourself!'
  error-notenoughmoneywithdraw: 'You can''t withdraw more than you have!'