# Infos
name: ConquestEconomy
version: '1.5.2'
description: A simple gold based Economy plugin that just works.
author: ConfusedAlex, Maroon28
api-version: 1.18

# Data
load: STARTUP
main: org.conquestmc.eco.ConquestEco
loadbefore: [Towny]
depend: [Vault, ItemsAdder]